name: Build NDK library
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - shell: bash
        run: mkdir toolchains
      - name: specify NDK
        uses: ravinderjangra/android-ndk-toolchain-setup@0.2
        with:
          api: '21'
          arch: 'arm'
          install-location: 'toolchains'
          force: true
      - shell: bash
        name: Download libgphoto2
        run: wget https://github.com/gphoto/libgphoto2/releases/download/v2.5.27/libgphoto2-2.5.27.tar.bz2
      - shell: bash
        name: Build with NDK
        run: tar -xvf libgphoto2-2.5.27.tar.bz2 && cp build.sh libgphoto2-2.5.27/build.sh && cd libgphoto2-2.5.27 && chmod +x build.sh && ./build.sh
